### PR TITLE
update datasets used in lecture cross_section

### PR DESCRIPTION
**Pull request by shlff**
Hi @jstac and @mmcky this PR updates datasets used in the lecture ``cross_section`` in the lecture python intro series:
- https://github.com/QuantEcon/lecture-python-intro/issues/119

To do:
- [x] add a ``README.md`` file to illustrate the datasets

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @shlff.  Please ping and work with @mmcky when this is ready for review.

**Comment by shlff** [comment]
Sure thanks @jstac . 

Hi @mmcky this PR is ready for review.

**Comment by mmcky** [comment]
@shlff I would suggest you add a table to the `README` that includes information about the datasets such as

| name | description | approx. size |
|------|-------------|-------------|
| <folder>/us_cities.txt | A dataset describing <someting> about cities in the US (<year>) | 32.4Mb |

and then include some instructions on how to fetch the data for use in a lecture (or elsewhere). 

These will be stored using `git-lfs` so can you fetch git-lfs directly in a lecture? Is that the aim. Perhaps we should have a quick zoom about what your requirements are here.

**Comment by shlff** [comment]
Thanks for your helpful comments @Matt ***@***.***>.

I will update the table and the instructions.

I can confirm that we can fetch git-lfs directly in a lecture. Please find the preview of this PR here:

  *   https://github.com/QuantEcon/lecture-python-intro/pull/123

I'd love for a quick zoom chat if you'd like.

Best,
Shu

  *

________________________________

**Comment by mmcky** [comment]
@shlff I see. I'm surprised this works given `git-lfs` are hashed commits but `GitHub` must resolve that link to its stored location. That's neat. I wonder what the size limit is. 

```python
df_fs = pd.read_csv('https://media.githubusercontent.com/media/QuantEcon/high_dim_data/update_csdata/cross_section/forbes-global2000.csv')
```

Seems that it is managed by QuantEcon data allowance and bandwidth usage. 

https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage

We have `50Gb` of storage and bandwidth so not binding in the medium term. But it will be interesting to see the usage as people start downloading datasets from our GitHub account using `python`

**Comment by shlff** [comment]
Thanks for your advice and chat @shlff . I've created an issue with the bandwidth usage: 
- https://github.com/QuantEcon/high_dim_data/issues/4

I will keep you posted once I update the data description and instructions.

**Comment by mmcky** [comment]
thanks @shlff if you're happy with this PR please go ahead and merge.

**Comment by shlff** [comment]
Thanks @mmcky . I've pushed some modifications to the instructions. Now the PR is ready for merging. 

I will also create a PR in repo [lecture-python-intro](https://github.com/QuantEcon/lecture-python-intro) to update the URL for the related lectures which use these datasets.

**Pull request merged**
